### ISSUE TITLE
Transition from form-data to built-in FormData API

### ISSUE THREAD

**Issue by rlajous** [poap-xyz/poap.js#44]
#### 📃 Description
We plan to transition from the `form-data` library to the built-in `FormData` API. The goal is to enhance compatibility across different environments and reduce the dependencies of our libraries.

#### 💡 Motivation
Adapting our library to use the built-in `FormData` interface, which is a part of the Web API in modern browsers and also supported in Node.js environments from certain versions, helps us adopt a more lightweight and standardized approach.

#### 🚀 Benefits

1. **Standardization**: Using `FormData`, part of most modern browsers, promotes standardization and reduces reliance on third-party libraries.
2. **Lightweight**: By removing the need for the `form-data` library, the total size of our library is significantly reduced, leading to faster load times.
3. **Future-proof**: As more developers adopt `FormData`, our library becomes more sustainable and future-proof.

#### ❗ Requirements
For using `FormData` in a Node.js environment, our library now requires Node.js version X or later due to `FormData` compatibility starting from this version.

#### 🏁 Conclusion
This transition aligns with our commitment to following modern standards, optimizing our libraries, and providing more robust and efficient tools for our users.

**Comment by ThaungThanHan** [comment]
I would like to work on this. Please !assign it to me.

**Comment by rlajous** [comment]
> I would like to work on this. Please !assign it to me.

We have already solved this issue! Want to help with another one?
