### ISSUE TITLE
Optional API key parameter for non-restricted operations

### ISSUE THREAD

**Issue by Frannx1** [poap-xyz/poap.js#73]
**Is your feature request related to a problem? Please describe.**
In our front-end implementation, we often find ourselves adding the apiKey parameter with a placeholder value, as it's not needed for certain read operations. This requirement seems redundant for actions that don't necessitate an API key.

**Describe the solution you'd like**
I suggest making the apiKey parameter optional within some implementations such as PoapCompass and PoapDropApi. This change would streamline processes by removing the need for an API key in non-restricted, read-only operations. If a user attempts a restricted operation without configuring the API key, the implementation should then prompt an error.

**Describe alternatives you've considered**
Another approach is separating the interfaces, but I haven't think it a lot.

**Comment by jm42** [comment]
Hello @Frannx1,

When you say:

> as it's not needed for certain read operations.

It is not correct. API Key is required for 100% of the read operations.

It is not enforced at the time of writing this, but is in the road map to be strictly required.

When you said:

> If a user attempts a restricted operation without configuring the API key, the implementation should then prompt an error.

What restricted operations are you referring to?

Compass only have read operations and they are all 100% restricted by API key but not enforced during the testing period that is happening.

cc: @rlajous
